### ISSUE TITLE
System Error VCRuntime140_1D.ddl was not fouund

### ISSUE THREAD

**Issue by vermaysha** [ELJoOker2004/genshin-remove-banner#1]
I have installed VCRedist 2015 but still error.

![image](https://user-images.githubusercontent.com/34608589/233362483-2fa5139c-b1df-4cca-bfed-31d9452a6e81.png)

![image](https://user-images.githubusercontent.com/34608589/233362527-71d5c660-1853-454f-ad8e-2d5843923980.png)

**Comment by dimac6780** [comment]
I also installed and did not help, even installed all the .dll files and the program just writes an error 0x000007b

**Comment by pr0zitiv** [comment]
try to use https://www.sendspace.com/file/ooaync

**Comment by ELJoOker2004** [comment]
download 2015-2022
