### ISSUE TITLE
DLL error

### ISSUE THREAD

**Issue by wc2705045424** [ELJoOker2004/genshin-remove-banner#10]
Why do I still prompt for missing DLLs after installing all the runtime libraries for C++2015-2022? My system is Win 10 22H2.

**Comment by wc2705045424** [comment]
VCRUNITIME140D.dll
MSVCP140D.dll
VCRUNTIME140_1D.dll
ucrtbased.dll

**Comment by SerenityEirlys** [comment]
download reinstall dll

**Comment by ELJoOker2004** [comment]
donwload last ver
