### ISSUE TITLE
Protection Question

### ISSUE THREAD

**Issue by waylaa** [ELJoOker2004/genshin-remove-banner#15]
Is disabling the cheat's protection safe? Its description is too vague. What does 'closes the mhyprot2 handle' mean? Does it increase any chance of a ban?

**Comment by ELJoOker2004** [comment]
closing the protection must be safer for u (it closes the protection of genshin) , btw almost all users even with this option on the mhyprot2 still not closed so it's useless option , the remover version 1.5 should work even if u didn't have protection disabled so u are fine anyway do what u prefer , if u had any other question feel free to dm me on discord ELJoOker#8401

**Comment by waylaa** [comment]
I understand now.  Thank you for explaining what it does. You should update the readme to include the fact that the remover works regardless of the protection (on or off).
