### ISSUE TITLE
Banner can't be removed although the program is working

### ISSUE THREAD

**Issue by PZJPANG** [ELJoOker2004/genshin-remove-banner#5]
![image](https://user-images.githubusercontent.com/55829580/233531279-72110c22-8e9e-48d3-93b7-2b7e65b901f4.png)
![image](https://user-images.githubusercontent.com/55829580/233531307-69f5abcb-6462-41fc-adc7-1ac16ec7db65.png)

**Comment by SerenityEirlys** [comment]
run as admin

**Comment by PZJPANG** [comment]
already run as admin but still didnt remove the banner

**Comment by SerenityEirlys** [comment]
> already run as admin but still didnt remove the banner
What version do you use?

**Comment by PZJPANG** [comment]
1.1and1.0 both are already tried

**Comment by SerenityEirlys** [comment]
Go me github have private version

**Comment by SerenityEirlys** [comment]
Ur cant dms me discord i support Eirlys#0001

**Comment by PZJPANG** [comment]
Friend request sent

**Comment by OzymoGit** [comment]
please release binary

**Comment by YungSamzy** [comment]
This can be fixed, just look at my [pull request](https://github.com/ELJoOker2004/genshin-remove-banner/pull/8)!

**Comment by ELJoOker2004** [comment]
make sure disable protection option is on
and make sure mhyprot handler is closed too 
this should work
